version: 3

tasks:
  # Local development with wrangler
  dev:wrangler:
    dir: apps/http-server
    desc: "Run the API locally using Wrangler (Cloudflare Workers runtime)"
    cmds:
      - bunx wrangler dev --env development

  secrets:set:prod:
    dir: apps/http-server
    desc: "Set secrets for production environment"
    interactive: true
    silent: false
    dotenv: ['../../.secrets.prod']
    cmds:
      - echo "Setting production secrets..."
      - |
        echo "🚨 whatever values are set in .env will override the secrets set in production"
        read -p "Press enter to continue..."
        echo -n "Setting production secrets..."

        echo -n "Setting DATABASE_URL... $DATABASE_URL"
        echo -n "$DATABASE_URL" | bunx wrangler secret put DATABASE_URL --env production

        echo "Setting GOTRUE_SERVICE_ROLE_KEY..."
        echo -n "$GOTRUE_SERVICE_ROLE_KEY" | bunx wrangler secret put GOTRUE_SERVICE_ROLE_KEY --env production

        echo "Setting JWT_SECRET..."
        echo -n "$JWT_SECRET" | bunx wrangler secret put JWT_SECRET --env production

        echo "Setting STRIPE_WEBHOOK_SECRET..."
        echo -n "$STRIPE_WEBHOOK_SECRET" | bunx wrangler secret put STRIPE_WEBHOOK_SECRET --env production

        echo "Setting STRIPE_SECRET_KEY..."
        echo -n "$STRIPE_SECRET_KEY" | bunx wrangler secret put STRIPE_SECRET_KEY --env production

        echo "Done setting production secrets"

  secrets:list:prod:
    dir: apps/http-server
    desc: "List secrets for production environment"
    cmds:
      - bunx wrangler secret list --env production

  tail:prod:
    dir: apps/http-server
    desc: "Tail logs from production environment"
    cmds:
      - bunx wrangler tail --env production

  # Build and type check
  build:
    dir: apps/http-server
    desc: "Build the API for production"
    cmds:
      - bun run lint
      - echo "Build complete - Cloudflare Workers uses source files directly"

  deploy:prod:
    dir: apps/http-server
    desc: "Deploy API to Cloudflare Workers (production environment)"
    cmds:
      - bunx wrangler deploy --env production

  deploy:prod:check:
    dir: packages/api
    desc: "Deploy to production with linting and type checks"
    cmds:
      - task: build
      - task: deploy:prod 

  stripe:webhook:listen:
    dir: packages/api
    desc: "Listen for Stripe webhooks"
    cmds:
      - stripe listen --forward-to localhost:3042/stripe/webhook